### ISSUE TITLE
Incorrect behavior when screen rotates

### ISSUE THREAD

**Issue by ncerezo** [evnaz/ENSwiftSideMenu#22]
When the screen rotates the menu does not update it's position, that leads to it to be visible if hidden and in the wrong place. It also makes it disappear if you try to hide/show it.
I'm making a pull request to fix it.

**Comment by animaonline** [comment]
Has this been fixed, I´m still seeing this issue.

**Comment by ncerezo** [comment]
It was fixed, but someone later on made the updateFrame function private.
You need to call that from didRotateFromInterfaceOrientation (iOS 7) or viewWillTransitionToSize (iOS 8) from the view controllers.
I'm using a subclass of UIViewController that makes the necessary calls, and then inheriting my controllers from it.
However, the fix worked only for iOS 8, since iOS 7 will not swap height and width when on portrait mode.
I'm working on a fix for both iOS 7 and iOS 8, will make the pull request soon. I'll make sure to put a big notice on updateFrame so no one will make it private again.

**Comment by ncerezo** [comment]
I just made a pull request fixing this.

**Comment by animaonline** [comment]
Yeah, I ended up using viewWillTransitionToSize and animateAlongsideTransition, but it still doesn't work correctly when the menu is positioned to the right.

This can be easily reproduced in the example project.

**Comment by ncerezo** [comment]
I'm using it with the menu positioned to the right, and it works with the changes I've submitted.
I've finally used viewDidLayoutSubviews, because it is a single call that works both for iOS7 and iOS8+ and because it really makes more sense, since it is a layout what is done.

**Comment by animaonline** [comment]
In my example I had over 30 items in it, so that could be the reason.

On Mon, May 11, 2015 at 1:04 PM, Narciso Cerezo <notifications@github.com>
wrote:

> I'm using it with the menu positioned to the right, and it works with the
> changes I've submitted.
> I've finally used viewDidLayoutSubviews, because it is a single call that
> works both for iOS7 and iOS8+ and because it really makes more sense, since
> it is a layout what is done.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/evnaz/ENSwiftSideMenu/issues/22#issuecomment-100869497>
> .
>



-- 
Roman Alifanov - MCAD - MCTS - MCP - MCT
http://www.animaonline.com
